### ISSUE TITLE
Support usage without jwt

### ISSUE THREAD

**Issue by psi-4ward** [nvonahsen/jitsi-token-moderation-plugin#2]
Hi,
thanks a lot for your plugin, seems to work great if a jwt was provided.
But if theres no JWT (`allow_empty_token = true`) no one becomes a mod. Can we use the standard behavior when theres no jwt so that the one who creates the room becomes a mod?

Next: I see the log msd `room created, adding token moderation cod` every 10 seconds in the logs.

**Comment by bryanasdev000** [comment]
Hi @psi-4ward !

I'm not 100% sure but maybe moving this `if origin.auth_token then` to the hook instead of the function could help, you may need to change the hook as well.

But this functionality kind of ignores the purpose of the plugin, right? Since you use JWT (and consequently this plugin) you would be integrating Jitsi in another application and controlling moderation from this application.

Your use case is valid if you use the server in a multi tennat scheme.

**Comment by psi-4ward** [comment]
Thanks for your answer. That was exact the case: smth like multi tennant. 

Some users create rooms on the fly an the first one should become a mod (without jwt).
But others with jwt should be able to join and then become mods. 

For now I've implemented a "pre-landing-page" which always generates a JWT with diff. settings for a specific room. 

I've had a look at the sources and could not find a good way to _merge_ the jitsi behave with some sane jwt overwrites. Meanwhile I think too much magic is not good option so we could close this topic.
